[build]
  command = "npm install && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "24"

[[redirects]]
  from = "https://www.artaufeminin.fr/*"
  to = "https://artaufeminin.fr/:splat"
  status = 301
  force = true
